# Generated by Django 5.2.7 on 2026-02-26 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('quantum_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Simulation Session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Rain', 'Rain'), ('Heavy Rain', 'Heavy Rain'), ('Fog', 'Fog'), ('Night', 'Night'), ('Sunset', 'Sunset')], default='Clear', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Condition',
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('classical', 'Classical'), ('quantum', 'Quantum')], max_length=10)),
                ('decision', models.CharField(default='Straight', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('steering_error', models.FloatField(default=0.0, help_text='Absolute steering deviation')),
                ('lane_deviation', models.FloatField(default=0.0, help_text='Absolute lane offset')),
                ('collision_flag', models.BooleanField(default=False)),
                ('weather', models.CharField(default='Clear', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='core.simulationsession')),
            ],
            options={
                'verbose_name': 'Decision Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steering_angle', models.FloatField(default=0.0, help_text='Steering angle [-1, 1]')),
                ('throttle', models.FloatField(default=0.0, help_text='Throttle [0, 1]')),
                ('brake', models.FloatField(default=0.0, help_text='Brake [0, 1]')),
                ('lane_offset', models.FloatField(default=0.0, help_text='Lateral offset from lane centre')),
                ('curvature', models.FloatField(default=0.0, help_text='Road curvature')),
                ('detected_sign', models.CharField(default='None', help_text='Traffic sign label', max_length=50)),
                ('decision', models.CharField(default='Straight', help_text='Driving decision', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Model confidence [0, 1]')),
                ('speed_kmh', models.FloatField(default=0.0, help_text='Vehicle speed in km/h')),
                ('weather', models.CharField(default='Clear', max_length=20)),
                ('model_type', models.CharField(default='quantum', help_text='classical or quantum', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_states', to='core.simulationsession')),
            ],
            options={
                'verbose_name': 'Vehicle State',
                'ordering': ['-timestamp'],
            },
        ),
    ]
